#spring.application.name=online-banking

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true